run:
  timeout: 1m
  skip-dirs:
  - example/client

linters:
  disable-all: true
  enable:
  #- unused
  - ineffassign
  - goimports
  - gofmt
  - misspell
  - unparam
  - unconvert
  - govet
  - errcheck
  - staticcheck

linters-settings:
  staticcheck:
    go: "1.18"
    checks:
    - "all"
    - "-SA1019"

 # unused:
    #go: "1.18"